apiVersion: v1
kind: ServiceAccount
metadata:
  name: vscode
  namespace: test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vscode-system-admin
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: cluster-admin
subjects:
- kind: ServiceAccount
  name: vscode
  namespace: test
---  
apiVersion: v1
kind: Pod
metadata:
  name: vscode-ubuntu
  namespace: test
  labels:
    app: vscode-ubuntu
spec:
    serviceAccountName: vscode
    containers:
    - name: vscode-ubuntu
      image: ghcr.io/ozlevka/vscode-deploy-cluster:latest
      command: 
      - /bin/bash
      - -c
      - "while sleep 1000; do :; done" 
